### ISSUE TITLE
CRC for Data Frames

### ISSUE THREAD

**Issue by mobilinkd** [M17-Project/M17_spec#11]
I would like to propose that we change the CRC of data frames to exclude the LICH.

The link setup frame (LSF) encoded in the LICH has its own CRC.  Adding the LICH data to the data frame CRC means that every LICH frame has to be decoded even when a valid LSF is available.  This adds an unnecessary cost to the demodulator.

Is there some other reason it would be necessary for each LICH to be decoded when a valid LSF is available and the data frames are being decoded?

**Comment by sp5wwp** [comment]
This is true. We can and should exclude the LICH chunk from the data frame CRC.
