### ISSUE TITLE
File formats for voice + data streams.

### ISSUE THREAD

**Issue by lwvmobile** [M17-Project/M17_spec#122]
I know its listed as TODO in the manual, but can you give me a quick low-down on the voice + data? Is it the same Stream frame setup as 3200 voice, but just use the first 64 bits as 1600 voice w/ 40 ms (320 samples) and the other 64 bit is data? Or the other way around. Or entirely different. I hunter all around your Github presence and couldn't find any clues in any code, so I wasn't sure of the set up for it. Thanks.

**Comment by kc1awv** [comment]
One of the implementations for 1600 V+D mode in M17 can be found in mvoice, I believe that this may be what you're looking for: 

here: https://github.com/n7tae/mvoice/blob/8e0a9fb350f8308d7ee7e07e3cc48e7c33a7be64/AudioManager.cpp#L121
and here: https://github.com/n7tae/mvoice/blob/8e0a9fb350f8308d7ee7e07e3cc48e7c33a7be64/AudioManager.cpp#L332

If not, we can try asking N7TAE and G4KLX about the implementations that they have and adjust the specification accordingly.

**Comment by kc1awv** [comment]
There's also this snip of code from G4KLX in M17RX.cpp that might be relevant:

```c
		// A valid M17 audio frame
		short audio[CODEC_BLOCK_SIZE];
		if (m_state == RS_RF_AUDIO) {
			m_3200.codec2_decode(audio + 0U,   frame + 2U);
			m_3200.codec2_decode(audio + 160U, frame + 2U + 8U);
		} else {
			m_1600.codec2_decode(audio + 0U,   frame + 2U);
			m_1600.codec2_decode(audio + 160U, frame + 2U + 4U);
			CUtils::dump(1U, "Data Payload", frame + 2U + 8U, 8U);
		}
```

**Comment by lwvmobile** [comment]
Okay, that might be enough to go on. If I read the code correctly, it does look like the second half of the 128-bit payload is the data portion, with the first 64-bit being the 1600 voice portion. I've already written the code in, so I guess at this rate, I won't really know for sure whether or not it works properly is if anybody raises an issue and says it does or doesn't. I don't suppose that the M17-Education repo could acquire some 1600 sample .rrc type files for testing purposes, or similar.

**Comment by kc1awv** [comment]
Wojciech found the missing part in the spec. I'll add it as soon as I can!
![obraz](https://github.com/M17-Project/M17_spec/assets/43918257/59bc8a27-3b94-4780-99af-ff7f0cff47f0)
