### ISSUE TITLE
AES/Scrambler Values seem to flip flop in the PDF

### ISSUE THREAD

**Issue by lwvmobile** [M17-Project/M17_spec#125]
![Screenshot from 2023-08-24 12-39-45](https://github.com/M17-Project/M17_spec/assets/59371473/109d0634-9aab-4986-8430-21b2ebd42e59)
![Screenshot from 2023-08-24 12-39-59](https://github.com/M17-Project/M17_spec/assets/59371473/c00522ab-25c1-4caa-bfa6-db59b5f3bcdc)
![Screenshot from 2023-08-24 12-40-26](https://github.com/M17-Project/M17_spec/assets/59371473/c930475d-c176-4791-b1e9-b54bae99d38e)
![Screenshot from 2023-08-20 20-34-26](https://github.com/M17-Project/M17_spec/assets/59371473/fc42f1ee-2499-4336-ae0c-be36d6667576)

Also, need clarification as to which value is the correct value, and also, if possible, can you advise on the key len for AES-CTR (M17-tools seems to use 128/192/256, while M17_implementations uses a hardset AES256 that isn't variable.

**Comment by sp5wwp** [comment]
I think `Table 2.8` has AES and Scrambler swapped.

**Comment by sp5wwp** [comment]
The only implementation in `M17_Implementations` doesn't support any encryption.

**Comment by lwvmobile** [comment]
> The only implementation in `M17_Implementations` doesn't support any encryption.

I misspoke on that, I meant to say `OpenHT-fw-test` which also uses the value of 1 for AES, and 2 for Scrambler.
![Screenshot from 2023-08-24 13-14-45](https://github.com/M17-Project/M17_spec/assets/59371473/d9917ec7-fafd-41bc-89b4-4434dc2fe980)

**Comment by kc1awv** [comment]
Resolved with #126

**Comment by lwvmobile** [comment]
I don't mean to be 'that guy', but that's currently the opposite of M17-tools does. They also use the value of 1 for AES.

![Screenshot from 2023-08-24 13-58-29](https://github.com/M17-Project/M17_spec/assets/59371473/a433316d-3cca-4ca7-a806-ffe4fbc426a2)

**Comment by sp5wwp** [comment]
I hope all is settled now.

**Comment by lwvmobile** [comment]
You're going to want to make the same change to m17-rtx-gui as well

https://github.com/M17-Project/m17-tools/blob/51d2cb4cc2a57d94899e79617379ab81e775fe1b/apps/m17-rtx-gui.cpp#L1036

And who knows where else those values are enumerated incorrectly at. I would assume since it was reversed in the mod tools, its probably also reversed on the demod tools. 

https://github.com/M17-Project/m17-tools/blob/51d2cb4cc2a57d94899e79617379ab81e775fe1b/include/m17cxx/LinkSetupFrame.h#L26

Not sure if there are any other places or not, those are just the ones I could find with a quick search.

**Comment by sp5wwp** [comment]
Fixed both.
