### ISSUE TITLE
Packet superframe - allowed payload size

### ISSUE THREAD

**Issue by sp5wwp** [M17-Project/M17_spec#132]
>Packet superframes are composed of a 1..n byte data type specifier, 0..797 bytes of payload
data.

I believe the value should be updated to `33*25-3=822`.

**Comment by mobilinkd** [comment]
Why? What changed to allow the additional frame of packet data?

**Comment by sp5wwp** [comment]
Packet frame number is 5-bit, so goes from 0 to 31. That gives space for 32 frames. The additional bit (End of Frame flag) is used to mark the 33rd frame, the frame number is then replaced with the number of bytes within the last frame.

**Comment by sp5wwp** [comment]
Closing with [f5dec5a](https://github.com/M17-Project/M17_spec/commit/f5dec5ab2f7003ee412dc644d1cddff1cd4ca728).
