### ISSUE TITLE
Link between Preamble and Sync Burst section

### ISSUE THREAD

**Issue by marcoSchr** [M17-Project/M17_spec#133]
At the moment, section 1.4.1 describes, that the preamble can be sequence of `(+3, -3)` or `(-3, +3)`.
When each of them is used is later described in section 2.4 Sync Burst in table 2.3.

It would be useful to link to section 2.4 or table 2.3 from the text of section 1.4.1 to clarify, when each type of preamble is used.

**Comment by sp5wwp** [comment]
Fixed.
