### ISSUE TITLE
Reasons for hardware choices

### ISSUE THREAD

**Issue by tomhajjar** [M17-Project/M17_spec#134]
1. Is the unit Full or Half Duplex? If Half, why no T/R switch?

2. Why use a bi-directional coupler and log amps on TX output? APC only needs a resistive divider feeding a detector IC like LTC5505.

3. Why use an output isolator? The RA60H3847 can handle fairly high VSWR.

**Comment by kc1awv** [comment]
Closing - out of context for the M17 Protocol spec.
