### ISSUE TITLE
Packet mode CRC

### ISSUE THREAD

**Issue by sp5wwp** [M17-Project/M17_spec#136]
CRC in the packet mode is calculated over the type indicator and payload. It includes the terminating null byte (in the case of SMS). Make sure that's mentioned in the spec document.

**Comment by lwvmobile** [comment]
So, is that includes, or excludes the initial data type identifier byte? I'm getting conflicting information between here and the issue in dsd-fme.

**Comment by sp5wwp** [comment]
> So, is that includes, or excludes the initial data type identifier byte? I'm getting conflicting information between here and the issue in dsd-fme.

I edited the entry above to reflect what's actually done in the implementation.

**Comment by sp5wwp** [comment]
Hopefully fixed in [bc47b12](https://github.com/M17-Project/M17_spec/commit/bc47b1296d64515976e7675a8814fc0ae1536c1c).
