### ISSUE TITLE
ALL == 0xffffffffffff is inconsistent.

### ISSUE THREAD

**Issue by n7tae** [M17-Project/M17_spec#139]
0x4ce1 decodes to 'ALL'. Reserved addresses for encoded callsigns should only be for things that can't be done with the M17Alphabet.

**Comment by sp5wwp** [comment]
What you propose keeps the encoding of 'special addresses' logical. The only problem I see is that every implementation would have to be updated, but that's more of an annoyance than a real problem.

**Comment by SmittyHalibut** [comment]
My original intent was to allow any arbitrary string to be used without having special meanings to how it's routed. Reserving strings out of the decodeable namespace seems less clean to me than using non-decodeable values to affect how the routing protocol works. Think of it like a non-printable control character. 

Whether that's a compelling argument or not, I'll leave up to @sp5wwp Im just explaining my original thinking when I wrote that bit.

**Comment by sp5wwp** [comment]
In any case, "ALL", "ECHO", "INFO" and "UNLINK" should occupy the same address space. This needs a change in one or the other direction.

**Comment by SmittyHalibut** [comment]
100% agree with that.  It needs to be consistent.  Again, I'm not pushing for one over the other, but I will push for consistency.

**Comment by g4klx** [comment]
I don’t agree. 0xFFFFFFF is only translated as ALL by the software for ease of understanding. It’s the broadcast address in the same was as 255.255.255.255 is. Also it allows it to be translated into whichever language is in use without being so anglocentric. I would argue that we should look at reserving a space around 0xFFFFFF to be used for special destinations like ECHO etc.

**Comment by kc1awv** [comment]
> I don’t agree. 0xFFFFFFF is only translated as ALL by the software for ease of understanding. It’s the broadcast address in the same was as 255.255.255.255 is. Also it allows it to be translated into whichever language is in use without being so anglocentric. I would argue that we should look at reserving a space around 0xFFFFFF to be used for special destinations like ECHO etc.

I agree. `#ALL` is just a "placeholder" text. It can literally be anything, and at least in previous versions of OpenRTX, it was `#BROADCAST` at one point, changed to `#ALL` because "amateur radio doesn't broadcast"

**Comment by SmittyHalibut** [comment]
I hadn't thought about the Anglocentricity.  (Ya know, being a native English speaker myself, that's a blind spot of mine...)  That's a very good point.

As for reserving space, base40() will only encode text strings up to a certain value that's very close to, but not quite, 2^48-1.  An alphabet of 40 characters, 9 characters long, 40^9.

2^48 - 40^9 = 19330976710656.

That entire space above 40^9-1 and below 2^48-1 can be used however we want without getting in the way of the base40() name space.  Conveniently, 0xFFFFFFFFFFFF is in that space unreachable by base40().

(Sorry if this ends up a dupe post. I replied to an email, but it doesn't appear to have made it into the Issue log.)

**Comment by n7tae** [comment]
Let me firmly reiterate my belief that anything that can be encoded with the forty M17 callsign character set should never be reassigned to the 'reserved' section of the address space.

I would like to broaden my original issue: I don't think anything about a client/repeater/gateway/reflector application should ever be part of the M17 Specification.

Specifically, that means:
- The introduction to the Applications sections should state that this section of the Specification will only cover various type of well defined, encapsulated data that can be optionally included in an M17 stream or packet along with specifications about how often a inclusion is to occur. The existing definition of the GNSS metadata (this section should have a subheading) is an excellent example of how this should look.
- Tables 3.2 and 3.3 needs to be deleted from the Specification. M17Gateway is outside the scope of the M17 Specification.
- All of section 4.2 needs to be deleted. The M17 reflector, mrefd, is outside the scope of the M17 Specification.
- In table A.1, delete the Broadcast line.
- The A.3 and A.4 coding example should not specially encode/decode 'ALL'.

Finally, It's my opinion that Appendix A should state that the nearly twenty trillion reserved addresses are for use by the M17 Project and that applications that use them risk being broken by the evolving M17 Specification.

I think that these changes will ultimately result in large, healthy, and active open-source environment for the M17 Project and in fact, all forms of digital ham radio.

**Comment by n7tae** [comment]
Strike my second to the last sentence. I really don't know what 'RESERVED' means in the Specification. Does it mean this is reserved for development by the M17 Project, or can any developer use these reserved address in their applications?

One more thing: The address 0x0 (encoded with nine spaces) might be more appropriate for a "broadcast" address because it means there is no specific destination address and therefore is going to everyone. But 0x0 is marked as INVALID in the Specification. 0x0 does have the advantage of not being language-centric.

**Comment by gdt** [comment]
Typically, in the land of standards, RESERVED means that you can't use it and that some future version of the standard might assign it.   Typically, there is a range of values marked for private use/experimental, but also an expectation that  widely distributing software using those is not a great idea.    When there is an intent to support people using a codepoint privately, there is often a registry so they can allocate one and not collide (e.g. TCP port numbers).  Often one must publish a protocol spec or at least describe use to register, but one does not need consensus that the proposed use is a good idea or the group's chosen path to solve that problem.

All that said, I am not 100% certain this is how the spec sees it.

**Comment by kc1awv** [comment]
> Does it mean this is reserved for development by the M17 Project, or can any developer use these reserved address in their applications?

The latter. The base-40 encoding of a 9 character string of the Latin alphabet, numbers and some punctuation only uses a portion of the valid address space. (Appendix A)

I agree that the wording 'for future use' is a bit confusing. Whose future use?

There was a reason that 0x0 isn't used, and 0xFFFFFFFFFFFF is at the end of the valid space, much like Ethernet broadcast MAC. A bit of Ethernet methodology was used when designing M17 layers.

**Comment by n7tae** [comment]
Okay, I happily yield. It seems like there is already some idea how these reserved addresses are to be carved up and assigned. I'm looking forward to understanding the plan and how it's going to affect my contributions.

Closing...

**Comment by n7tae** [comment]
Sorry, I closed this prematurely. Reopened...

**Comment by sp5wwp** [comment]
@n7tae is this fixed now?

**Comment by sp5wwp** [comment]
Fixed with [cfb6733](https://github.com/M17-Project/M17_spec/commit/cfb6733d8d16c0f0aa2af324d63b167ea5d9611d).
