### ISSUE TITLE
IP encapsulation spec is reflector specific

### ISSUE THREAD

**Issue by nivex** [M17-Project/M17_spec#52]
The IP Networking section (`docs/ip_encapsulation.rst`) of the specification refers specifically to reflectors throughout. While this is currently the only method of doing M17 Internet linking, a healthy discussion happened on chat today that brought about the notion of a system that could route packets based on the encapsulated packet's destination field.

I therefore propose:
* all references to "reflector" in this specification be changed to the more generic "server"
* the module parameter (byte 10) to the CONN command
  * be made optional
  * be further explained that its purpose is for reflector use and a link to the reflector documentation be included

If we are not amenable to having the module parameter be optional, I propose an additional character '+' be allowed to indicate the client expects destination field routing instead of reflector style functionality.

**Comment by sp5wwp** [comment]
Out of scope.
