### ISSUE TITLE
ARNCE?

### ISSUE THREAD

**Issue by darconeous** [M17-Project/M17_spec#87]
Howdy, I saw that you were encoding callsigns in a similar way to the mechanism I came up with a few years ago: https://github.com/arngll/arnce-spec/blob/main/README.md#amateur-radio-numeric-callsign-encoding-readme

I put a lot of thought into the addressing mechanism, which includes translations to EUI-48 and EUI-64, as well as multicast, etc.

Just figured you would be interested in having a look.

Also, you might be interested in having a look at [ARNGLL](https://github.com/arngll/arngll-spec/blob/main/n6drc-arngll.md#introduction), which is a project that I have been very slowly developing over the past several years.

**Comment by darconeous** [comment]
I've added a [functional comparison with M17](https://github.com/arngll/arnce-spec/blob/main/n6drc-arnce.md#m17) to the ARNCE spec.

**Comment by sp5wwp** [comment]
Closing, as we have that part of the specification fixed already with a multitude of implementations.
